-- ==========================================
-- DealDone Master Schema Setup Script
-- Run this entire script in the Supabase SQL Editor
-- ==========================================

-- 1. Reset (Optional - careful!)
-- drop table if exists messages;
-- drop table if exists businesses;

-- 2. Businesses Table
create table if not exists businesses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  owner_id uuid references auth.users not null,
  name text not null,
  industry text not null,
  revenue numeric,
  valuation numeric,
  description text
);

-- Enable RLS for Businesses
alter table businesses enable row level security;

-- Business Policies
-- (Drop existing policies first to allow re-running script safely)
drop policy if exists "Public businesses are viewable by everyone" on businesses;
create policy "Public businesses are viewable by everyone"
  on businesses for select
  using ( true );

drop policy if exists "Owners can insert their own business" on businesses;
create policy "Owners can insert their own business"
  on businesses for insert
  with check ( auth.uid() = owner_id );

drop policy if exists "Owners can update their own business" on businesses;
create policy "Owners can update their own business"
  on businesses for update
  using ( auth.uid() = owner_id );


-- 3. Messages Table
create table if not exists messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false
);

-- Enable RLS for Messages
alter table messages enable row level security;

-- Message Policies
drop policy if exists "Users can read their own messages" on messages;
create policy "Users can read their own messages"
  on messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

drop policy if exists "Users can send messages" on messages;
create policy "Users can send messages"
  on messages for insert
  with check ( auth.uid() = sender_id );

-- 5. Email Notification Function
-- This function sends an email when a new message is received
create or replace function notify_new_message()
returns trigger as $$
declare
  receiver_email text;
  sender_name text;
begin
  -- Get receiver's email
  select email into receiver_email
  from auth.users
  where id = NEW.receiver_id;
  
  -- Get sender's name
  select raw_user_meta_data->>'full_name' into sender_name
  from auth.users
  where id = NEW.sender_id;
  
  -- Send email notification using Supabase's built-in email service
  -- Note: This requires Supabase email templates to be configured
  perform pg_notify(
    'new_message',
    json_build_object(
      'receiver_email', receiver_email,
      'sender_name', coalesce(sender_name, 'A user'),
      'message_preview', substring(NEW.content, 1, 50)
    )::text
  );
  
  return NEW;
end;
$$ language plpgsql security definer;

-- Create trigger for new messages
drop trigger if exists on_new_message on messages;
create trigger on_new_message
  after insert on messages
  for each row
  execute function notify_new_message();

-- 4. Initial Mock Data (Optional - creates a demo seller and listings)
-- Only runs if the user doesn't exist yet
DO $$
DECLARE
  demo_user_id uuid := 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11';
BEGIN
  -- Insert Demo User if not exists
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE id = demo_user_id) THEN
    INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_user_meta_data)
    VALUES (demo_user_id, 'demo_owner@dealdone.app', 'password123', now(), '{"full_name": "Demo Seller", "type": "owner"}');
  END IF;

  -- Insert Mock Listings if they don't exist
  IF NOT EXISTS (SELECT 1 FROM public.businesses WHERE owner_id = demo_user_id) THEN
    INSERT INTO public.businesses (owner_id, name, industry, revenue, valuation, description)
    VALUES 
      (demo_user_id, 'Nexus AI Solutions', 'Technology', 2500000, 12000000, 'Leading AI-driven analytics platform for retail chains.'),
      (demo_user_id, 'GreenLeaf Organics', 'Food & Beverage', 850000, 2200000, 'Established organic grocery brand with 3 brick-and-mortar locations.'),
      (demo_user_id, 'SwiftShip Logistics', 'Logistics', 5500000, 4800000, 'Regional freight forwarding company with fleet of 50 vehicles.'),
      (demo_user_id, 'Urban Fits', 'Retail', 1200000, 3000000, 'Trendy streetwear brand with high social media engagement.');
  END IF;
END $$;
