-- Create the Businesses Table
create table businesses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  owner_id uuid references auth.users not null,
  name text not null,
  industry text not null,
  revenue numeric,
  valuation numeric,
  description text
);

-- Turn on Row Level Security
alter table businesses enable row level security;

-- Policies
-- 1. Everyone can view businesses (for the buyer dashboard)
create policy "Public businesses are viewable by everyone"
  on businesses for select
  using ( true );

-- 2. Owners can insert their own businesses
create policy "Owners can insert their own business"
  on businesses for insert
  with check ( auth.uid() = owner_id );

-- 3. Owners can update their own businesses
create policy "Owners can update their own business"
  on businesses for update
  using ( auth.uid() = owner_id );


-- NEW: Messages Table
create table messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false
);

alter table messages enable row level security;

-- Users can read messages sent to them OR sent by them
create policy "Users can read their own messages"
  on messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

-- Users can insert messages where they are the sender
create policy "Users can send messages"
  on messages for insert
  with check ( auth.uid() = sender_id );
